### 01 - Coleta de Dados

Este notebook realiza a primeira etapa do pipeline de dados do projeto: a coleta de informações públicas do YouTube relacionadas à repercussão do ECA Digital no contexto dos jogos eletrônicos no Brasil.

A coleta utiliza a YouTube Data API v3 e contempla três principais tipos de dados:
- metadados dos vídeos encontrados a partir de palavras-chave;
- métricas de engajamento dos vídeos, como visualizações, curtidas e quantidade de comentários;
- comentários públicos associados aos vídeos coletados.

Os dados obtidos nesta etapa serão armazenados em formato CSV na camada `data/raw`, preservando os dados em seu estado bruto para posterior tratamento, análise exploratória e processamento de linguagem natural.

In [1]:
import sys
from pathlib import Path
import pandas as pd

Como o projeto foi organizado de forma modular, as funções auxiliares e configurações foram separadas dentro da pasta `src`.

Para garantir que o notebook consiga importar esses módulos corretamente, o diretório raiz do projeto é adicionado ao caminho de busca do Python.

In [2]:
ROOT_DIR = Path.cwd().parent

if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

In [3]:
from src.config import (
    YOUTUBE_API_KEY,
    DIRETORIOS_PROJETO,
    PALAVRAS_CHAVE,
    REGION_CODE,
    RELEVANCE_LANGUAGE,
    MAX_VIDEOS_POR_TERMO,
    MAX_COMENTARIOS_POR_VIDEO,
    RAW_DATA_DIR
)

from src.data_utils import (
    criar_diretorios,
    salvar_csv,
    remover_duplicados
)

from src.youtube_api import (
    criar_cliente_youtube,
    coletar_videos_por_palavras_chave,
    buscar_estatisticas_videos,
    adicionar_estatisticas_aos_videos,
    coletar_comentarios_dos_videos
)

Antes de iniciar a coleta, são criados os diretórios definidos no arquivo de configuração do projeto.

Esta etapa garante que os dados coletados sejam armazenados de forma organizada, separando os dados brutos, dados processados, arquivos finais e saídas geradas durante a análise.

In [4]:
criar_diretorios(DIRETORIOS_PROJETO)

A conexão com a YouTube Data API v3 é realizada por meio de um cliente autenticado com a chave da API armazenada no arquivo `.env`

A chave não é inserida diretamente no código por questões de segurança e boas práticas, evitando a exposição de informações sensíveis no repositório do projeto.

In [5]:
youtube = criar_cliente_youtube(YOUTUBE_API_KEY)

Os termos de busca foram definidos com base no tema central do projeto: a repercussão do ECA Digital no contexto dos jogos eletrônicos, da infância, da adolescência e da segurança digital.

A utilização de diferentes palavras-chave amplia a cobertura da coleta, permitindo recuperar vídeos que abordam o tema por perspectivas distintas, como regulação, proteção infantil, jogos online, influenciadores infantis e adultização no ambiente digital.

In [6]:
PALAVRAS_CHAVE

['Estatuto Digital da Criança e do Adolescente',
 'ECA Digital',
 'ECA Digital jogos',
 'ECA Digital jogos online',
 'ECA Digital games',
 'Lei do ECA Digital',
 'Lei Felca ECA Digital',
 'Lei 15211 ECA Digital',
 'proteção infantil na internet',
 'proteção infantil jogos online',
 'segurança infantil jogos online',
 'crianças e adolescentes jogos digitais',
 'regulação jogos digitais crianças',
 'regulação de jogos online para crianças',
 'adultização infantil internet jogos',
 'influenciadores infantis jogos',
 'crianças internet jogos online',
 'adolescentes jogos online segurança',
 'riscos dos jogos online para crianças',
 'exposição infantil jogos digitais',
 'plataformas digitais crianças adolescentes']

Nesta etapa, são coletados vídeos públicos do YouTube a partir das palavras-chave configuradas no projeto.

Para cada termo de busca, a API retorna um conjunto limitado de vídeos, priorizando resultados em português e associados ao Brasil. Cada vídeo coletado contém informações básicas, como título, descrição, canal, data de publicação, palavra-chave de origem e link de acesso.

In [7]:
videos = coletar_videos_por_palavras_chave(
    youtube = youtube,
    palavras_chave = PALAVRAS_CHAVE,
    max_videos_por_termo = MAX_VIDEOS_POR_TERMO,
    region_code = REGION_CODE,
    relevance_language = RELEVANCE_LANGUAGE,  
)

len(videos)

df_videos = pd.DataFrame(videos)
df_videos.head()

,video_id,titulo,descricao,canal,canal_id,data_publicacao,palavra_chave,link_video
0,ULsXFfByK6A,Estatuto Digital da Criança e Adolescente | Le...,Slides: https://drive.google.com/file/d/1GOgLJ...,Ricardo Torques,UCfEeo5EJkespOLV1_CosT3Q,2025-09-22T23:39:06Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=ULsXFfByK6A
1,oQmr7Ymh008,ECA Atualizado 2026 [AULA 01] Estatuto da Cria...,AULA 01 – ECA ATUALIZADO 2026 | CURSO PARA CON...,Prof. Joel Oliveira,UC5PYxebbhLbfwTgxlLDQleQ,2026-02-07T17:00:06Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=oQmr7Ymh008
2,eZFs2XDAHQ0,Lei da Adultização. Tudo sobre a nova Lei digi...,Tudo sobre a Nova Lei Digital da Criança e do ...,CP Iuris,UCGMQy-Md6MyTLRnPzRhI3DA,2025-09-20T06:44:51Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=eZFs2XDAHQ0
3,OYYk-DhaoD0,ESTATUTO DA CRIANÇA E DO ADOLESCENTE - ECA Atu...,PRIMEIROS PASSOS NO DIREITO: o método para que...,Me Julga - Cíntia Brunelli,UC40OzicC7y57ZtXtZHYylZQ,2022-12-13T15:15:01Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=OYYk-DhaoD0
4,NRCEt_GGnUs,ECA Digital: O que muda para pais e professore...,ECA Digital 2026: A Nova Lei que Mudou a Segur...,NeuroSaber,UCghJZXv-Cg90zgdeTZCt_-A,2026-03-24T13:00:46Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=NRCEt_GGnUs

Como um mesmo vídeo pode aparecer em mais de uma busca, é necessário remover registros duplicados com base no identificador único do vídeo.

Essa decisão evita que um mesmo conteúdo seja contabilizado mais de uma vez nas próximas etapas da análise.

In [8]:
df_videos = remover_duplicados(df_videos, subset="video_id")
df_videos.shape

(318, 8)

Após a coleta dos metadados básicos, são buscadas as estatísticas de engajamento de cada vídeo.

Essas métricas são importantes para avaliar a repercussão dos conteúdos, permitindo observar quais vídeos possuem maior alcance e interação do público.

In [9]:
videos_id = df_videos["video_id"].tolist()

estatisticas = buscar_estatisticas_videos(youtube=youtube, video_ids=videos_id)
len(estatisticas)

Erro ao buscar estatísticas dos vídeos. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/videos?part=statistics&id=imHN0bD-Xro%2C5d5t5nAhnNA%2CMGefXuChRLk%2CFrG_NKHeSRw%2Cfzt4_ZNRMxA%2CpniLENxecwo%2Ccy7sm2wJTaQ%2CCpmfg8zTYmk%2CgJTJPN8tfLI%2CRLCrRFJbV1I%2Csjws0rTPb34%2CXMZyJ4-X6o8%2C4sgL93uYmsI%2CjahufA1maU4%2CiiyB4aFn174%2C4_8bICrBO9U%2CkiIFkBYTBf0%2CgPnDJBxM7Jo%2Cza5ixWg9eTk%2CUlwTkdGJD6Q%2CP_67rAKin1s%2CF3wGDObxues%2CUYW_c1bDV8A%2C3MFvU8csj80%2CvZQoiElQYHU%2C9DO_AOtxUKo%2C2_Bq3k0BEu0%2C8vlPYxH0pFU%2CmdfrYElHNPw%2C7M7sRB0EwI0%2CyflHO8Rii4o%2C0FLv2rg16GQ%2CzZigZ-nMITY%2CysjJcP6ZsDU%2CrUC9L1xjpUE%2CTGcS4hJskU0%2CEB43sgI9cSg%2CC5oSZ-golGY%2CF9-Z3aavTEA%2CeHgf38Pfy1Y%2CyBuEQv7-BXA%2CMakCoz-JU0A%2CbhlN13chuhU%2CEL2V6jQ4bJQ%2CRn6TEuRjFtw%2Cvkj-WsaAMGI%2C-g06texaASk%2CAoTnUUwkitg%2CPXO2ApQnFDY%2C2keY-JLFsXw&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">

50

In [10]:
videos_com_estatisticas = adicionar_estatisticas_aos_videos(
    videos = df_videos.to_dict(orient="records"),
    estatisticas = estatisticas
    
)

df_videos = pd.DataFrame(videos_com_estatisticas)
df_videos.head()

,video_id,titulo,descricao,canal,canal_id,data_publicacao,palavra_chave,link_video,visualizacoes,likes,quantidade_comentarios
0,ULsXFfByK6A,Estatuto Digital da Criança e Adolescente | Le...,Slides: https://drive.google.com/file/d/1GOgLJ...,Ricardo Torques,UCfEeo5EJkespOLV1_CosT3Q,2025-09-22T23:39:06Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=ULsXFfByK6A,2502,254,13
1,oQmr7Ymh008,ECA Atualizado 2026 [AULA 01] Estatuto da Cria...,AULA 01 – ECA ATUALIZADO 2026 | CURSO PARA CON...,Prof. Joel Oliveira,UC5PYxebbhLbfwTgxlLDQleQ,2026-02-07T17:00:06Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=oQmr7Ymh008,71870,4025,166
2,eZFs2XDAHQ0,Lei da Adultização. Tudo sobre a nova Lei digi...,Tudo sobre a Nova Lei Digital da Criança e do ...,CP Iuris,UCGMQy-Md6MyTLRnPzRhI3DA,2025-09-20T06:44:51Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=eZFs2XDAHQ0,3435,154,16
3,OYYk-DhaoD0,ESTATUTO DA CRIANÇA E DO ADOLESCENTE - ECA Atu...,PRIMEIROS PASSOS NO DIREITO: o método para que...,Me Julga - Cíntia Brunelli,UC40OzicC7y57ZtXtZHYylZQ,2022-12-13T15:15:01Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=OYYk-DhaoD0,520404,29749,655
4,NRCEt_GGnUs,ECA Digital: O que muda para pais e professore...,ECA Digital 2026: A Nova Lei que Mudou a Segur...,NeuroSaber,UCghJZXv-Cg90zgdeTZCt_-A,2026-03-24T13:00:46Z,Estatuto Digital da Criança e do Adolescente,https://www.youtube.com/watch?v=NRCEt_GGnUs,25930,932,23

Os dados dos vídeos são salvos em formato CSV na pasta `data/raw`.
Neste momento, os dados ainda são considerados brutos, pois passaram apenas por uma remoção básica de duplicidades e ainda não receberam tratamento textual, normalização ou filtragens analíticas mais avançadas.

In [11]:
caminho_videos_raw = RAW_DATA_DIR / "videos_youtube_raw.csv"
salvar_csv(df_videos, caminho_videos_raw)

caminho_videos_raw

WindowsPath('C:/Users/odrgu/Desktop/pipeline-dados-eca-digital/data/raw/videos_youtube_raw.csv')

Além dos metadados e métricas dos vídeos, também são coletados comentários públicos associados aos vídeos encontrados.

Os comentários são especialmente relevantes para o projeto, pois representam manifestações diretas dos usuários e serão utilizados em análise de opinião, frequência de termos, sentimentos e percepção pública sobre o tema.

In [12]:
comentarios = coletar_comentarios_dos_videos(
    youtube = youtube,
    video_ids = videos_id,
    max_comentarios_por_video = MAX_COMENTARIOS_POR_VIDEO)


len(comentarios)

Não foi possível coletar comentários do vídeo oQmr7Ymh008. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=oQmr7Ymh008&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo eZFs2XDAHQ0. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=eZFs2XDAHQ0&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo OYYk-DhaoD0. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=OYYk-DhaoD0&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo NRCEt_GGnUs. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=NRCEt_GGnUs&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo JLD8i2sfagQ. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=JLD8i2sfagQ&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo j-dYSRzY3TI. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=j-dYSRzY3TI&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo hq0t4lEIsEw. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=hq0t4lEIsEw&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo huwACN1L-Ck. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=huwACN1L-Ck&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo 0JYoiIyTeLs. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=0JYoiIyTeLs&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo SM7RB9509Ts. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=SM7RB9509Ts&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo STtpqpLk-4k. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=STtpqpLk-4k&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo fnN7DaHAVEw. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=fnN7DaHAVEw&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo BUOGU1O54KA. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=BUOGU1O54KA&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo kvROwKdfciA. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=kvROwKdfciA&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo 1MGznw8FQyA. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=1MGznw8FQyA&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo Dtp6zntlzfE. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=Dtp6zntlzfE&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo lKHBSKdh2yU. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=lKHBSKdh2yU&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo MLu8nLpgqYE. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=MLu8nLpgqYE&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo nn3h_GI1BcU. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=nn3h_GI1BcU&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo kd5Wq47nDx0. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=kd5Wq47nDx0&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo AEhPqXeK4ak. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=AEhPqXeK4ak&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo Up0s7zz8P-0. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=Up0s7zz8P-0&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo EwT-Jz8jwXc. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=EwT-Jz8jwXc&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo rIfWRBHwC2o. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=rIfWRBHwC2o&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo ceOt8dPDQ1o. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ceOt8dPDQ1o&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo Y_W9V8ktyY0. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=Y_W9V8ktyY0&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo yNrS8zg6Cls. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=yNrS8zg6Cls&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo eQKAsXENgVs. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=eQKAsXENgVs&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo HBdVxseDJgU. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=HBdVxseDJgU&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo JOPphejAqzg. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=JOPphejAqzg&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Não foi possível coletar comentários do vídeo gy4MnpK-JJI. Detalhes: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=gy4MnpK-JJI&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyDajuiNmlst_9r1tlN-uoMxzWUNG2zOf3w&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">

9

In [13]:
df_comentarios = pd.DataFrame(comentarios)
df_comentarios.head()

,video_id,comentario_id,texto_comentario,data_comentario,likes_comentario
0,ULsXFfByK6A,Ugxz4zQdZt353mCd2Ed4AaABAg,Isso vai gera um colapso social e mental nas c...,2026-01-18T14:31:04Z,1
1,ULsXFfByK6A,UgzeC552aWdD2r7ixMN4AaABAg,Tô fazendo meu TCC com base nisso❤,2025-12-13T13:46:51Z,1
2,ULsXFfByK6A,UgyojUxdlip-LOZ3r0R4AaABAg,Obrigado pela aula! Você é um ótimo professor!...,2025-09-30T00:35:49Z,1
3,ULsXFfByK6A,UgywwQ2hsM16DbAifi94AaABAg,Caramba!!!!!Tanto estardalhaço por nada!!!O pr...,2026-05-06T22:12:32Z,0
4,ULsXFfByK6A,UgyrRaLG8iRQlpl9mj94AaABAg,Eu com 11 anos jogando Batman Arkham Knight pe...,2026-01-18T14:33:53Z,0

Assim como ocorre com os vídeos, os comentários também podem ser verificados quanto à duplicidade.

A remoção de comentários duplicados é feita com base no identificador único do comentário, garantindo maior consistência para as próximas etapas do pipeline.

In [14]:
if not df_comentarios.empty:
    df_comentarios = remover_duplicados(df_comentarios, subset=["video_id", "comentario_id"])
    df_comentarios.shape

Os comentários coletados são salvos separadamente dos dados dos vídeos.

Essa separação facilita as próximas etapas do projeto, pois os vídeos e os comentários possuem naturezas diferentes: os vídeos serão utilizados principalmente para análise de alcance e engajamento, enquanto os comentários serão utilizados para análise textual e processamento de linguagem natural.

In [15]:
caminho_comentarios_raw = RAW_DATA_DIR / "comentarios_youtube_raw.csv"
salvar_csv(df_comentarios, caminho_comentarios_raw)

caminho_comentarios_raw

WindowsPath('C:/Users/odrgu/Desktop/pipeline-dados-eca-digital/data/raw/comentarios_youtube_raw.csv')

Ao final da coleta, é realizada uma verificação inicial dos dados obtidos.

Essa etapa não corresponde ainda à análise exploratória completa, mas permite confirmar se os arquivos foram gerados corretamente, quantos registros foram coletados e quais campos estão disponíveis para as próximas fases do projeto.

In [16]:
print(f"Total de vídeos coletados: {len(df_videos)}")
print(f"Total de comentários coletados: {len(df_comentarios)}")

Total de vídeos coletados: 318
Total de comentários coletados: 9

In [17]:
display(df_videos[[
    "titulo",
    "canal",
    "data_publicacao",
    "visualizacoes",
    "likes",
    "quantidade_comentarios",
    "palavra_chave"
]].head())

display(df_comentarios[[
    "video_id",
    "texto_comentario",
    "data_comentario",
    "likes_comentario"
]].head())

,titulo,canal,data_publicacao,visualizacoes,likes,quantidade_comentarios,palavra_chave
0,Estatuto Digital da Criança e Adolescente | Le...,Ricardo Torques,2025-09-22T23:39:06Z,2502,254,13,Estatuto Digital da Criança e do Adolescente
1,ECA Atualizado 2026 [AULA 01] Estatuto da Cria...,Prof. Joel Oliveira,2026-02-07T17:00:06Z,71870,4025,166,Estatuto Digital da Criança e do Adolescente
2,Lei da Adultização. Tudo sobre a nova Lei digi...,CP Iuris,2025-09-20T06:44:51Z,3435,154,16,Estatuto Digital da Criança e do Adolescente
3,ESTATUTO DA CRIANÇA E DO ADOLESCENTE - ECA Atu...,Me Julga - Cíntia Brunelli,2022-12-13T15:15:01Z,520404,29749,655,Estatuto Digital da Criança e do Adolescente
4,ECA Digital: O que muda para pais e professore...,NeuroSaber,2026-03-24T13:00:46Z,25930,932,23,Estatuto Digital da Criança e do Adolescente

,video_id,texto_comentario,data_comentario,likes_comentario
0,ULsXFfByK6A,Isso vai gera um colapso social e mental nas c...,2026-01-18T14:31:04Z,1
1,ULsXFfByK6A,Tô fazendo meu TCC com base nisso❤,2025-12-13T13:46:51Z,1
2,ULsXFfByK6A,Obrigado pela aula! Você é um ótimo professor!...,2025-09-30T00:35:49Z,1
3,ULsXFfByK6A,Caramba!!!!!Tanto estardalhaço por nada!!!O pr...,2026-05-06T22:12:32Z,0
4,ULsXFfByK6A,Eu com 11 anos jogando Batman Arkham Knight pe...,2026-01-18T14:33:53Z,0

### Considerações finais da coleta

A primeira etapa do pipeline foi concluída com a coleta de dados públicos do YouTube relacionados ao tema do projeto.

Foram gerados dois conjuntos de dados brutos:
-  `videos_youtube_raw.csv`: contém metadados e métricas de engajamento dos vídeos coletados;
- `comentarios_youtube_raw.csv`: contém comentários públicos associados aos vídeos.

Esses arquivos serão utilizados nas próximas etapas do projeto, que envolvem tratamento dos dados, limpeza textual, análise exploratória e preparação para aplicação de técnicas de processamento de linguagem natural.